### ISSUE TITLE
[ISSUE] Crash when adding a Rest Period

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/FACETS#53]
**Application Version**

0.0.7-rc1 - 0.0.7-rc2

**Issue Description**
Crash occurs when returning home after adding a rest period.

**Stack Trace** (From Crashlytics)
```
Fatal Exception: java.lang.IllegalStateException: Fragment RSWRoutineHomeFragment{d813795} not attached to a context.
       at androidx.fragment.app.Fragment.requireContext(Fragment.java:696)
       at androidx.fragment.app.Fragment.getResources(Fragment.java:760)
       at uk.ac.bournemouth.facets.Fragments.RestSleepWakeRoutine.RSWRoutineHomeFragment$9.onComplete(RSWRoutineHomeFragment.java:556)
       at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:180)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:853)
```

**Comment by davcpas1234** [comment]
Issues with Context attachment have been resolved and will be released in `0.0.7-rc3`
